# Generated by Django 3.0.8 on 2020-07-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('placeID', models.AutoField(primary_key=True, serialize=False)),
                ('placeName', models.CharField(max_length=200)),
                ('business_status', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=200)),
                ('vicinity', models.CharField(max_length=100)),
                ('price_level', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('users_rating_num', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=400)),
                ('img_path', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('ethnicity', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.FloatField(default=0)),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apps.Place')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apps.User')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0)),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apps.Place')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apps.User')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ManyToManyField(to='apps.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.CharField(max_length=1000)),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apps.Place')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apps.User')),
            ],
        ),
    ]
