# Generated by Django 3.0.8 on 2020-07-16 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('placeID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('placeName', models.CharField(max_length=50)),
                ('business_status', models.CharField(max_length=50)),
                ('vicinity', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('price_level', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('users_rating_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('username', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('ethnicity', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.IntegerField(default=0)),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apps.Place')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apps.User')),
            ],
        ),
    ]
