# Generated by Django 3.0.8 on 2020-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='placeName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_rating',
            field=models.FloatField(default=0),
        ),
    ]
