# Generated by Django 3.0.8 on 2020-07-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200728_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(null=True),
        ),
    ]
