# Generated by Django 3.0.8 on 2020-07-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20200729_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
