# Generated by Django 3.0.8 on 2020-07-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
