# Generated by Django 3.0.8 on 2020-08-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20200729_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
